### ISSUE TITLE
Server Logs Async Function Results

### ISSUE THREAD

**Issue by shaunsmith** [fnproject/fn#1096]
**Description**

Async call logs do not contain function output to stderr.  Rather they contain server constructed output that embeds the result of the function.  There are two issues here:
1. Log contents for the same function configured either sync or async are completely different
2. Potentially sensitive user data is being captured in the logs

**Steps to reproduce the issue:**
1. Create a boilerplate Go or Node function, which does not specify `type` and so is `sync`.
2. Deploy the function
3. Call the function
4. Examine the logs of the call.  They will be empty as neither Go nor Node log to stderr.
5. Add `type: async` to the `func.yaml` and redeploy
6. Call the function
7.  Get the log and see that it contains output like:
```
{"body":"{\"message\":\"Hello World\"}","content_type":"application/json","protocol":{"status_code":200}}
```

**Describe the results you expected:**
 
It's debatable whether it's a problem that the logs for an async function contain anything that the function itself didn't produce--we can see the success or failure in the call details.  But the log *should not* contain the function result which may contain sensitive user data.

**Output of `fn version` (CLI command):**

```
Client version: 0.4.113 is not latest: 0.4.115
Server version:  0.3.470
```

**Comment by rdallman** [comment]
this has come up from @denismakogon as well so let's do something. the easiest solutions I can think of:

* change fdks to not accumulate output into STDOUT nor return a formatted response (e.g. `http` format). this would mean STDOUT just gets logged normally like STDERR.
* change fn to ignore STDOUT of async tasks altogether.
* change fn to receive a formatted STDOUT response (i.e. same as sync) but rather than log it, allow a user to use some 'hook' to do something with it (idk, maybe call a function with it, queue a message with it, whatever they want) as brought up in https://github.com/fnproject/fn/issues/469 we likely need something along these lines and it's not clear whether this hook should be an fn function or a go function (either are... interesting).

changing the fdks makes our container contract a bit longer (i.e. `if TYPE=async`) and is a bit, albeit relatively easy, more work than, say, just changing fn to ignore STDOUT for async tasks. up to us, possibly other things we could do here.

**Comment by shaunsmith** [comment]
The current situation is actually worse that I thought.  When I add logging to stderr in my sync function `fn get log myapp CALLID` correctly returns the text I had sent to stderr.  But when I switch to async the log contains the same JSON as above *without* my stderr output!

Clearly we're using logs differently for the sync and async cases so the question is should we be doing this?  Probably not. 

**Option 1:** From the call details I know the success or failure of the function which is great.  In the current async log behaviour I get extra fields that I don't think help me so why capture them?  If we don't believe the async log contents add value then it should contain the function stderr output just like for sync.

**Option 2:** If, on the other hand there's an argument to be made that having more details in the log is useful for sync functions then we should capture stderr and add it to the JSON object we're using for async.  The API would return the JSON object which the CLI could parse to make it easier to read/and or just return the stderr output by default or all fields when verbose requested.

But we should not be capturing stdout in any scenario.  Function results may/likely contain sensitive data.  However, capturing stderr is expected behaviour and it's on the developer to not log sensitive stuff.

**Comment by rdallman** [comment]
interesting, yeah it's supposed to write out both (stderr like normal and stdout according to a certain format), could be a bug there but we do have some tests for that I know (at one point at least we did). we can remedy that one quickly I think.

 option 1 makes the most sense to me, re: not capturing stdout at all, it almost seems like more of a bug on the part of the user to give STDOUT from an async function. I don't have too strong of feelings personally on STDOUT inclusion, it does seem a bit bizarre to hide it (and the sentiment generally is that it's bizarre to have it the same as sync output).

**Comment by zootalures** [comment]
Stdout should go to /dev/null for async. "We did nothing with the output of your function.... as requested"
