### ISSUE TITLE
Passing arguments to docker run

### ISSUE THREAD

**Issue by Kuvesz** [fnproject/fn#1117]
Hey!

I have a question, that may sound dumb, but who knows. I am looking for a way to pass command line arguments to docker run when starting a container. Is that possible right now?

Thanks in advance.

**Comment by zootalures** [comment]
Assuming you are referring to function containers and not the service continer, Fn doesn't let  you specify arbitrary docker arguments, typically these will be exposed via features of Fn itself. 

Fn aims to make functions portable, scalable, secure and consistent across a large range of environments,  (including, eventually environments that aren't running docker (e.g. Kubernetes, clear containers etc.)). 

In order to do that we have to restrict the means by which functions  can become specific to their environments by definition - unfortunately adding arbitrary docker commands would allow functions to (e.g.) mount containers and open ports which in turn could compromise the portability of those functions.

**Comment by zootalures** [comment]
If you are interested in adding a specific feature here please say though  - there are a lot of features that can feasibly be added without exposing docker args to users.

**Comment by rdallman** [comment]
the last question has been answered: https://stackoverflow.com/questions/51441703/how-to-change-driver-from-docker-to-mocker/51565330#51565330 -- as far as hooking that up to `fn run`, that is a whole can of worms we can open on the CLI repo if we get there :)

our stance is as stated, we can add features for certain things but it's not easy for us to add arbitrary flags around docker run in function invocations for the service itself (as we're not shelling out to `docker run`). thanks!
