### ISSUE TITLE
Where to specify CORS options

### ISSUE THREAD

**Issue by pavsidhu** [fnproject/fn#1143]
I'm setting up CORS for an Fn function, however from reading the [docs](https://github.com/fnproject/fn/blob/1258baeb7f2760727d504b0448f9b507b1bdbc07/docs/operating/options.md) it appears I need to set the environment variable `FN_API_CORS_ORIGINS` to set the `Acccess-Control-Allow-Origin` header.

Since I'm using docker in docker, I'm struggling with where I should specify the variable. The docs say to add variables using `docker run -e VAR_NAME=VALUE` however I deploy the functions for Fn to manage it, I don't need to ever use `docker run`.

I've tried to add the following to my Dockerfile with no success even though the variable is available to when I log it in my function:

`ENV FN_API_CORS_ORIGINS=*`

So where would I specify the variable?

**Comment by pavsidhu** [comment]
I managed to find a workaround adding the following to my `func.yaml` file:

```
headers:
  Access-Control-Allow-Origin:
  - https://localhost:3000
```

However it isn't the best solution to the issue.

**Comment by rdallman** [comment]
> However it isn't the best solution to the issue.

open to ideas here if you have suggestions, setting headers on the function are useful for separating the function from having to do this. it's also an option to return the headers directly from your function in the response, these will get propagated back out to the http response. if you're using an fdk this is easier to do, otherwise the details for setting response headers depend on the format (details are here: https://github.com/fnproject/fn/blob/master/docs/developers/function-format.md)

marking this as resolved, happy to discuss further here though. I see these are in our API docs relatively clearly explained as is (though happy to bolster if you've got suggestions)
