### ISSUE TITLE
How to call another function in one function?

### ISSUE THREAD

**Issue by WhoisZihan** [fnproject/fn#1255]
I think I saw it before somewhere but I can't find it anymore...

I have a master-workers model, master function will decide different strategies for workers, and all the workers will deal with the same data with decided strategies, then master will collect and compare their results. All workers should do their work simultaneously. Master and worker may be built with different languages(go and python).

However, I don't find a way to directly do that in fdk-go/fdk-python. I don't need Flow either because it calls the next function only after the previous one is finished, while I want something like a map-reduce model.

Is there any way to do so in fdk? Or should I just manually launch a http request to trigger them? If it is the latter, how can I pass custom data to it instead of using test.json, ~~~and how can the master collect workers' results?~~~ (I guess I can encode it inside http request)

Thanks.

**Describe the results you expected:**
I can call other functions within a function 

**Output of `fn version` (CLI command):**

```
Client version is latest version: 0.5.8
Server version:  0.3.588
```

**Additional environment details (OSX, Linux, flags, etc.):**
* Ubuntu 16.04.5
* Started using `fn start` without any options.

**Comment by denismakogon** [comment]
Hi and welcome! There are plenty of ways to call your function. First of all, with a new fn-2-trigger model you have exactly 2 ways to call a function:
 - invoke API (HTTP POST only)
 - HTTP trigger API (supporting all HTTP methods)

With an invoke API all you need is a function ID that you'd want to call.
All you need is to use the following pattern: 

`<fn-api-url>/invoke/{fn_id}` 

(for instance, `http://localhost:8080/invoke/01CQR004J4NG8G00GZJ0000002`)

With an HTTP trigger API, you may need an app name and trigger path, URL pattern:

`<fn-api-url>/t/{app}/{trigger_path}`

(for instance `http://localhost:8080/t/testapp/test-trigger`).

The trigger path is what you specify in fn's trigger section in your `func.yaml`:
```yaml
triggers:
- name: test-trigger
  type: http
  source: /test-trigger
```

So, in order to bypass the next function ID or trigger path you may configure them through a function's config.

Please note, with an invoke API all your custom HTTP headers will appear as is, but with an HTTP triggers all your custom headers will be prefixed with `Fn-Http-H-`. At this moment, we work hard on bringing a coverage for a new `http-stream` format, it will speed up your functions due to certain tech improvements we did in Fn recently. Currently only FDK-go|java support that, FDK-python and FDK-node are the next ones.

With an FDK changes, we'd change the context contract and an FDK will provide 2 different contexts:
 - invoke context (is the default one your function receives)
 - http context (can be instantiated from an invoke context, An HTTP context will decap/encap your HTTP headers)

I hope this would help.

**Comment by denismakogon** [comment]
You've mentioned `test.json` if you're referring to `fn test` - it will go away in a day or two. The only way to test your functions is to write your own unit tests that would not use Fn at all.

**Comment by WhoisZihan** [comment]
Thanks a lot for your timely reply. But how can I get the function id from fdk-python? `fn list functions pythonapp` only shows the function name and image, not the fn_id. Also, could you show where to put custom data when doing invoke, should I put it into http header or into body with json?

About the `http-stream`, if I get it right, do you mean fdk-python is slower but workable, or it is not compatible right now?

Lastly as for the `test.json`, I did not run `fn test`, instead, I directly run `fn deploy --app myapp --local` and it seems that the function responds with the data in test.json.

**Comment by WhoisZihan** [comment]
Another thing(perhaps irrelavant) is that I've noticed fdk-python provides decorations
`@decorators.fn(fn_type="sync", dependencies={
        "requests_get": requests.get
    })`
Can I achieve my goal with `fdk.application.decorators.fn` and `fn_type="async"`? So that I can create many functions in just one python file rather than creating lots of .py files.

**Comment by denismakogon** [comment]
> But how can I get the function id from fdk-python? fn list functions pythonapp only shows the function name and image

You can get fn ID with `fn inspect fn <app>  <fn>`

> Also, could you show where to put custom data when doing invoke, should I put it into http header or into body with json?

`echo -e '{"key": "value"} | 'fn invoke <app> <fn>` or use `curl` for the rest of things.

> About the http-stream, if I get it right, do you mean fdk-python is slower but workable, or it is not compatible right now?

`http-stream` PR merged, a new version `0.0.34` of FDK-python released less than an hour ago.

> But how can I get the function id from fdk-python?

With `ctx.FnID()` you may get your current Fn ID, but only works with FDK `0.0.34`

> Another thing(perhaps irrelavant) is that I've noticed fdk-python provides decorations
@decorators.fn(fn_type="sync", dependencies={ "requests_get": requests.get })
Can I achieve my goal with fdk.application.decorators.fn and fn_type="async"? So that I can create many functions in just one python file rather than creating lots of .py files.

That code is outdated and needs to be fixed later.

**Comment by denismakogon** [comment]
@WhoisZihan Fn apps decorators will work again shortly (https://github.com/fnproject/fdk-python/pull/54). There was a need to switch to Fn API V2 to work with triggers/fns. So, now it works again, all I need is an approval from other team members to land the PR and release `0.0.35` version.

**Comment by denismakogon** [comment]
Closing this for now. If you'd like to ask more questions - feel free to hit me on [Slack](https://join.slack.com/t/fnproject/shared_invite/enQtMjIwNzc5MTE4ODg3LTdlYjE2YzU1MjAxODNhNGUzOGNhMmU2OTNhZmEwOTcxZDQxNGJiZmFiMzNiMTk0NjU2NTIxZGEyNjI0YmY4NTA).

**Comment by WhoisZihan** [comment]
Hi @denismakogon I know this has been closed for a few days, but I tried HTTP trigger API today and it keeps giving me

> {"message":"error receiving function response"}

Here is the directory of my example application (Both root function and sub function are written in Go, deployed with `fn deploy --all --local`)

```
.
├── app.yaml
├── func.go
├── func.yaml
├── Gopkg.toml
├── LICENSE
└── LRFunction
    ├── func.go
    ├── func.yaml
    └── Gopkg.toml
```

The root function can decide different strategies for each LRFunction, and LRFunction will just do simple calculation.

I am sure LRFunction is working because I can get correct result directly from it if I bypass root function (command is `echo -e '{"name": "example", "dataset": "1,2,0.62,1,3,0.85,2,3,0.98", "params": "0.13,0.23"}' | fn invoke cvalid cvalid-serverless`).

I did almost the same as the source code of fn cli, except that I use HTTP trigger API rather than invoke API. Here is the code snippet in root function, which calls LRFunction
```C++
var modelTrigger = map[string]string{
	"LRFunction": "http://localhost:8080/t/k-fold/lrfunction-trigger",
}

func invokeModel(model string, data []byte, wg *sync.WaitGroup) {
	defer wg.Done()

	// This line gets the trigger url from an array
	triggerURL := modelTrigger[model]
	req, err := http.NewRequest("POST", triggerURL, bytes.NewReader(data))

	httpClient := http.Client{Transport: http.DefaultTransport}
	resp, err := httpClient.Do(req)
	defer resp.Body.Close()
	if err != nil {
		fmt.Println("Error in model " + model)
		return
	}
	// other stuff
}
``` 

Then I get the 502 error, am I missing anything?

I thought about invoke API that fn cli source uses, but that would make the function more complicated, so I'd like to see if I can do it in pure HTTP API.

Thanks

**Comment by denismakogon** [comment]
Maybe because your root function can't talk to localhost. If you want to call one function from another you need to make your Fn run over the public IP, but not on the localhost. For fast prototyping try https://ngrok.com to get a public IP address.

**Comment by denismakogon** [comment]
Also, you need to check your function logs (for that you need to set up the syslog or papertrail) to see what's going on.

`{"message":"error receiving function response"}` also means that your function is corrupted somehow, you need to debug that.

**Comment by WhoisZihan** [comment]
Thanks, I will try ngrok first.

About the log, does Fn only support sending log to server through network? The same question for retrieving result of async function, it seems the only way is sending it to `X-callback-url`?

**Comment by denismakogon** [comment]
In Fn API v2 there’s no async functions, for now. Http triggered function works in sync mode only.

And yes, our logs API as it is right now will go away, so, the only way is to use syslog.

**Comment by WhoisZihan** [comment]
I see, but why removing async functions in v2, it doesn't seem useless anyway.

**Comment by denismakogon** [comment]
A new type of almost-async function’s will be delivered as a new trigger with a 1-2 month.

**Comment by WhoisZihan** [comment]
I get it. Thanks,
