### ISSUE TITLE
Broken syslog should not cause problems to a function execution 

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#1306]
**Description**

Assume you've configured an application with a syslog (Papertrail, Logstash, etc.) but for some reason it got broke.
It appears that broken syslog blocks the execution of a function.

**Steps to reproduce the issue:**
1. create an app and a function
2. setup Papertrail account, get the logging URL
    2.1. `fn update app testapp --syslog-url="tcp+tls://logs7.papertrailapp.com:43074` (you can actuall use this one because this one was revoked).
3. Revoke papertrail account.
4. Call a function, see Fn logs.

**Describe the results you received:**
A sequence of the following erros in Fn logs:
```
time="2018-11-09T18:48:51Z" level=warning msg="docker temporary error, retrying" app_id=01CQR004HQNG8G00GZJ0000001 cpus= docker_cmd=StartContainer error="API error (500): failed to initialize logging driver: dial tcp 169.46.82.186:40277: connect: connection refused" fn_id=01CV7DSCTMNG8G00GZJ0000001 id=01CVWWVD2PNG8G00GZJ0000009 idle_timeout=30 image="denismakogon/word-generator:0.0.14" memory=256
```
leads to:
```
ime="2018-11-09T18:49:16Z" level=error msg="internal server error" action="server.handleFnInvokeCall)-fm" error="API error (500): failed to initialize logging driver: dial tcp 169.46.82.186:40277: connect: connection refused" fnID=01CV7DSCTMNG8G00GZJ0000001
```

**Describe the results you expected:**
I actually not sure what i was expecting to get since i missed the whole thing about revoking/updating my app with a new papertrail instance.
But i assume that broken syslog might not be a problem for the invocation, no?

**Comment by rdallman** [comment]
thanks, this is interesting and seems like a behavior we should try to document and allow users to get a useful error message on at least. an argument could likely be made either way probably that if logs can't connect users may or may want functions to run regardless, but yea, I'd imagine most people would rather have their functions run and not get logs than not run. 

seems like a good policy would be retry connect a few times (bound this) and then maybe try to start the container without the logging driver attached eventually? we'd need to make sure this error is user visible somehow probably, which is tricky without logs, so that users can see that their logging driver didn't connect when they ask why they aren't getting logs - metrics would be a good place for that, maybe, but we don't have a good story there, either. any thoughts/ideas?

**Comment by skinowski** [comment]
This is a know problem and it's the limitation of docker-syslog driver. We can open a bug with them.

**Comment by denismakogon** [comment]
@skinowski I think that's the best we can do in a short term.

**Comment by rdallman** [comment]
it's also an option to go back to doing these ourselves and get behavior we want (and call ids), but then we have the networking problem (ie container must have outbound access that can reach log service)

**Comment by rdallman** [comment]
we've at least improved this error https://github.com/fnproject/fn/pull/1402 - closing?
