### ISSUE TITLE
FN_API_URL and a path

### ISSUE THREAD

**Issue by tuempeltaucher** [fnproject/fn#1339]
FN_API_URL="https://fqdn:9999/root-path" fn version

Client version: 0.5.29 is not latest: 0.5.33
Server version:  ?

server's logfile:

Dec  4 14:15:40 cl-dc1-nodeXXX fabio: 2018/12/04 14:15:40 [WARN] No route for fqdn:9999/version

It seems that fn ignores the path from FN_API_URL.

I tried a custom context:

$ fn list context
CURRENT	NAME	PROVIDER	API URL						REGISTRY
	default	default		http://localhost:8080				
*	nms	default		https://fqdn:9999/root-path	

Does not change anything.

**Comment by melrom** [comment]
I have the same issue with client 0.5.40 on OSX.

**Comment by vzDevelopment** [comment]
Hi, I am unable to replicate this. Would it be possible to try again with the latest version and let me know if it's working for you now? I'm assuming it has been fixed.

In order to try and replicate this I ensured nothing was running on the default `localhost:8080` (just to ensure fn wasn't ignoring the environment variable completely), started an fnserver on port 8081, and then setup a local reverse proxy that forwarded `/fn/` to `http://localhost:8081/`.

```
vzarola-Mac:myapp2 vzarola$ echo $FN_API_URL
http://127.0.0.1:8888/fn/

vzarola-Mac:myapp2 vzarola$ fn list app
NAME	ID
myApp	01D7KMK6SZNG8G00GZJ0000001
myapp2	01D7J3TSJ8NG8G00GZJ0000004

vzarola-Mac:myapp2 vzarola$ fn version
Client version is latest version: 0.5.69
Server version:  ?
```

After terminating the reverse proxy I got:
```
vzarola-Mac:myapp2 vzarola$ fn list app

Fn: Get http://127.0.0.1:8888/fn/v2/apps: dial tcp 127.0.0.1:8888: connect: connection refused

See 'fn <command> --help' for more information. Client version: 0.5.69
```

**Comment by rdallman** [comment]
> "https://fqdn:9999/root-path" 

thanks @vzDevelopment for looking into this - I believe the issue from the OP is because they are using a non-root path, and `FN_API_URL` only works with the `scheme://host:port` part of the url. can see that we're stripping it from the error message:

`No route for fqdn:9999/version`

where the user was expecting:

`https://fqdn:9999/root-path/version`

this is probably something we can support pretty easily, though I'm not 100% sure.

**Comment by vzDevelopment** [comment]
Ah I see the issue is isolated to the `fn version` command. I misunderstood and thought none of the commands were working e.g. `fn list app`.

I think the cause for this is [this line](https://github.com/fnproject/fn_go/blob/4d7d200044b7cdbbcd5558260473d3f6fa4dd57a/provider/defaultprovider/default_provider.go#L68). It needs changing to use `op.FnApiUrl.Path` like [this line](https://github.com/fnproject/fn_go/blob/4d7d200044b7cdbbcd5558260473d3f6fa4dd57a/provider/oracle/oracle_provider.go#L135).

Before change:
```
vzarola-Mac:testing vzarola$ echo $FN_API_URL
http://127.0.0.1:8888/fn/
vzarola-Mac:testing vzarola$ fn version
Client version is latest version: 0.5.69
Server version:  ?

# Proxy Logs
CONNECT   Apr 04 20:35:16 [85721]: Request (file descriptor 10): GET /version HTTP/1.1
```

After change:
```
vzarola-Mac:testing vzarola$ echo $FN_API_URL
http://127.0.0.1:8888/fn/
vzarola-Mac:testing vzarola$ fn version
Client version is latest version: 0.5.69
Server version:  0.3.687

## proxy logs
CONNECT   Apr 04 20:33:58 [85721]: Request (file descriptor 10): GET /fn/version HTTP/1.1
```

I'll create a PR
