### ISSUE TITLE
Adding currently hot function information (appId, functionId, image name) to prometheus

### ISSUE THREAD

**Issue by SamTS** [fnproject/fn#1365]
Currently `/metrics` only shows the count of current paused/started/waiting/etc functions. It would be useful if it also showed which specific functions were paused/started/waiting/etc, for purposes such as load balancing and or just getting better stats about exactly what functions are hot.

Sample output:
fn_container_paused_function{app_id="id1", function_id="id2", image_name="sampleImage:0.1.2"}
fn_container_paused_function{app_id="id3", function_id="id4", image_name="sampleImage2:0.2.3"}

**Comment by rdallman** [comment]
we're using opencensus for this tagging, the docs for going about this are https://godoc.org/go.opencensus.io/tag#example-New and there are a lot of examples in our code if you search `tag.New` - since the container path and the request path split off, this should be easy to do near the top of checkLaunch or runHot in agent.go without polluting the request metrics at all, i'd expect app_id and fn_id to already be present so I'm surprised they aren't. we may want to just do the tagging of the context inside of UpdateState to minimize the number of metrics that get the image name tag, though I think we maybe should only have app_id and fn_id since image can be deduced from the function id (with the exception that it can change and we don't have versions, but this may be okay to start)

**Comment by SamTS** [comment]
Made the changes [here](https://github.com/fnproject/fn/pull/1373). It's waiting for Oracle CLA.
