### ISSUE TITLE
Invoke call doesn't return Fn Http Headers if the fn doesn't return a body. (LB configration only)

### ISSUE THREAD

**Issue by reclaro** [fnproject/fn#1413]
**Description**
When Fn is configured in LB configuration there is a bug related to custom HTTP Header not returned in case the function doesn't return a body.
The problem here is in the writeResp method in the agent.go, precisely the problem is due to the io.Copy:
https://github.com/fnproject/fn/blob/73778de0ae919268d2fa293001ea6546269d7c82/api/agent/agent.go#L746

the code for io.Copy doesn't call the <dst>.Write if the source is empty:
https://golang.org/src/io/io.go?s=14042:14087#L403
In our case the dst is a http.ResponseWriter and if we don't call the write we skip the send of the "RunnerMsg_ResultStart" which is where we include the custom Headers defined by the function:
https://github.com/fnproject/fn/blob/73778de0ae919268d2fa293001ea6546269d7c82/api/agent/pure_runner.go#L441

As a result of that we won't see custom headers sent back to the caller if the function return an empty body or doesn't return a body at all.

**Comment by reclaro** [comment]
I have a fix ready to be submitted soon.

**Comment by rdallman** [comment]
@reclaro thanks for figuring the details out here. It seems like it's possible that we're not implementing the http.ResponseWriter contract appropriately, either. from https://golang.org/pkg/net/http/#ResponseWriter 

```
        // Header returns the header map that will be sent by
        // WriteHeader. The Header map also is the mechanism with which
        // Handlers can set HTTP trailers.
        //
        // Changing the header map after a call to WriteHeader (or
        // Write) has no effect unless the modified headers are
        // trailers.
```

this would seem to say that `WriteHeader` should write the headers (generally with http there's a buffer here so that the headers and early body bits are written in one go instead of 2, we probably want similar behavior, but I haven't thought about details with 2 RPC messages there it may be trickier), instead of currently our behavior is that headers are not set until Write time. From https://github.com/fnproject/fn/blob/73778de0ae919268d2fa293001ea6546269d7c82/api/agent/agent.go#L746 we are appropriately calling WriteHeader before that, and Write itself should call WriteHeader as well if it has not been called yet either, I am not sure we're doing this either.

**Comment by reclaro** [comment]
The version I pushed now move the send of the RunnerMsg_ResultStart when we call WriteHeaders.
In this commit we call the WriteHeaders from Write as well as it is supposed to be. Please note that when we send the RunnerMsg_ResultStart message now we use enqueueMsgStrict which, in the event of errors, cause the callHandler to shutdown. WriteHeader interface doesn't return an error so shutting down the callHandler is a way to signal the error and avoid to ignore it. In the code we have in master if we see any errors during the send of RunnerMsg_ResultStart during the Write call, the Write return that error now that is not the case anymore. What do you think about this change?
