### ISSUE TITLE
traces: adding opencensus grpc handler into runner, pool

### ISSUE THREAD

**Issue by bharadwr** [fnproject/fn#1513]
Some grpc traces are being missed out in runner_client.go and static_pool.go due to the lack of opencensus grpc wrappers (https://godoc.org/go.opencensus.io/plugin/ocgrpc#ClientHandler and https://godoc.org/go.opencensus.io/plugin/ocgrpc#ServerHandler), this will add some details to my internal work as well. 

More span attributes/tags could be added to call.go and agent.go at spans agent_submit, agent_call_start and agent_call_end.

It also looks like the tag at https://github.com/fnproject/fn/blob/master/api/agent/agent.go#L240,L249 isn't being added into the trace. Unsure if others are having this issue

**Comment by rdallman** [comment]
> It also looks like the tag at https://github.com/fnproject/fn/blob/master/api/agent/agent.go#L240,L249 isn't being added into the trace. Unsure if others are having this issue

hmm, from https://github.com/fnproject/fn/pull/1472 it looks like I was seeing the call id in the trace in jaeger from the image pasted there, I wonder if it's just not carried across the grpc boundary? I remember the tags themselves being somewhat confusing to set up / propagate but I've since forgotten the details of my confusion there. maybe this adds some clarity.

**Comment by bharadwr** [comment]
Might just be our faas setup, I'll take a closer look. thanks reed!
