### ISSUE TITLE
lock gofn project

### ISSUE THREAD

**Issue by avelino** [fnproject/fn#388]
A relatively new project developed and maintained by @nuveo for container (via Docker socket) processing local or remote (IaaS, digital ocean support today)

`gofn` will not be a software, it is package (one of the premises).

I see much fit among the projects, does the `gofn` can help `fn` somehow?

**Comment by rdallman** [comment]
Hi @avelino our project is unrelated to `gofn` though they look similar in nature, `gofn` seems to be about running docker containers as tasks easily inside of go code where our project aims to be more of an api level way to execute code and we provide added sugar to run consecutive tasks quickly against the same container. I am not sure about using `gofn` inside of our project as we do some kind of gnarly operations for interacting with the docker api to swap out writers and such so that we can run multiple tasks against the same container, so we just need lower level access, but do see how `gofn` could be useful for people running docker tasks who don't want to do all of the docker wiring.

thanks for the feedback, looks like a useful project.
