### ISSUE TITLE
32bit Version

### ISSUE THREAD

**Issue by DQvsRA** [fnproject/fn#407]
Could you please create 32bit version?

Error: you are not using a 64bit platform.
Functions CLI currently only supports 64bit platforms.

![image](https://user-images.githubusercontent.com/442111/31342004-a289871e-ad0b-11e7-893b-db12e1f90a6d.png)

**Comment by rdallman** [comment]
this issue is slightly misleading, the cli will likely build with 32 bit. concerns would be supporting a 32-bit download from the cli link, we could do this relatively easily it's just a wart to support it forever if there are few users and it proves hard to maintain for whatever reason. the other concern is that the cli itself relies on docker as well as portability of those images, which I simply haven't read into at all, but supporting arm has similar issues.

in any event, closing this from this repo as the CLI has moved to https://github.com/fnproject/cli -- please re-open there if you'd like. thanks for filing this!
