### ISSUE TITLE
[Feature] Create, deploy, call a function

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#429]
Intro
----
At this moment user performs two actions against functions:

- user creates it (`fn routes create ...`)
- user calls it (`fn call ...`)

each call to a function is bound by certain timeout. 
For user this timeout means that within given time frame function should respond, but at Fn side we try to pull image and start container from it, so if container is big enough ( in my particular case 3.5Gb) one or more calls would fail because first call to a function would not be able to pull image in fast and user will get HTTP 504 Timeout for multiple attempts. Temporary fix is to set huge timeout on first call.

Taking into account that user expects to get nearly the same  execution time as he would run the same code locally, such behaviour makes UX unpredictable.

So, this issue here to make every step explicit:

- user should create a function (`fn routes create ...`)
- user should deploy a function (`fn routes deploy ...`)
- user should calls it (`fn call ...`)

How is it different from current behaviour?
-------------------------------------------
Well, `fn routes deploy` will do all implicit work explicit - it will make Fn verify and pull an image.

Impact on DB models
---------------------
Route model will have new field  - is_deployed (type `bool`, default `false`)

API impacts
------------
New (or updated) HTTP path - `/v1/{app}/routes/{route}?action=deploy`
User would not be able to call a function if it's not deployed

Questions to answer
---------------------
Would we reject route delete if function was undeployed (i.e send HTTP request `/v1/apps/{app}/routes/{route}?action=updeploy`)?

Related issues
--------------
TBD

**Comment by carimura** [comment]
i've always used the sequence `fn run` then `fn deploy` (with --local if testing locally) then `fn call`. The deploy alias makes this explicit.

A broader question (maybe orthogonal to your particular issue) is that we have essentially command groups around "images" and "routes" but not "functions" when this is in fact a "functions as a service" API.

**Comment by denismakogon** [comment]
@carimura current deploy doesn't really make Fn to pull an image, that's why with big images causing few calls to newly created route to fail because first call will initiate image pull and only following next call might succeed or fail again if image pulling is still in progress.

**Comment by carimura** [comment]
oh right i see what you're saying... pulling the image to the machine.

**Comment by rdallman** [comment]
think this is being thought about in really small terms, only thinking about this demo case (not that we shouldn't improve it, but..)

> Route model will have new field - is_deployed (type bool, default false)

as long as `fn deploy` does things in a reasonable sequence, then we can be pretty assured that functions will always be deployed after they are uploaded because: image upload happens before route update. if this is not the case, we should just do that. we don't need to encode this data into the models / db / api. i see all kinds of ux bugs here ("hey man my function is deployed but it says it isn't deployed..."). hopefully rule this out... bigger issue is:

> Well, fn routes deploy will do all implicit work explicit - it will make Fn verify and pull an image.

this is just thinking really specific to demos/local, we're typically going to run in cluster mode and this presents multiple issues:

### routing

the server handling the deploy request will be the only one with the image. this means that our routing algorithm needs to map to this server. currently, routing has extremely low memory overhead since we can just use a hash function. using this, we'd need to modify things to make sure that these requests go to the same place. otherwise, this results in us right back at square 1. this is solvable, but it adds obvious unnecessary complexity.

### bloat

fn is going to be pulling images across a lot of different servers since any deploy will trigger a pull. this means that even if images are never ran or ran only much later, we're bloating down fn servers with images that at a minimum we don't know if they will run (we can't know). this means even if we do have a good cleaner that runs every, say, hour, deploying a function that doesn't run for 12 hours results in 2 pulls. if images are poorly made (>1GB) then this is wasted gigs of bandwidth and disk that have to compete with normal traffic, slowing other things down spuriously.

### plumbing issue

now we're going to have to plumb out just pulling images up to a different endpoint, where right now they're contained inside of the driver layer somewhat nicely, since they're really only needed when trying to run them anyway.

### doesn't really fix the problem

if you make a call immediately after a deploy you will still have to wait [for pull], even if if was started in another thread. so even adding this does not fix the problem at all, it shaves maybe 1s off it. so we're getting a lot of cons for the pro of 1s. i don't buy that. lambda, GCF, et al all have this exact same issue where the first invocation takes much longer than immediately succeeding requests. it is obviously a problem we should try to handle gracefully, but there's no making the image magically appear. waiting for it on the routes update endpoint, that endpoint is just going to timeout and users won't know if their function is deployed (worse issue), and makes it much harder to make the 'update function' operation atomic. it's likely better UX for us to have an error that says 'image still pulling' + timeout, and this is something composable that we/users can use to retry user requests in clients or the load balancer -- some functions may have an image on 10 machines, and we're trying to run on an 11th, so we can just fall back to trying on number 9 and have it run immediately. this seems preferable and likely the more common case in practice than the 0->1 (scaled numbers will win). this also happens to be very preferable to waiting on image pulls on first requests when that may take 10+ minutes (if, say, the image is >1GB) and may even fail, not to mention the load balancer will timeout. 

hopefully point made, mostly against this specific proposal but agree that improving the 0->1 case would be nice and appreciate starting the convo (and detailed proposal) so we can start thinking about it. to be somewhat constructive, i think since we're really just trying to optimize this demo case, aside from trying to make smaller images, it seems like we should probably retry automatically in `fn call` perhaps just to make things smooth and possibly as proposed make a more explicit error about the image not being ready yet so that users can do things with that info (like retry).

**Comment by denismakogon** [comment]
As far as i remember, before agent we have dedicated timeout for pulling an image. I do understand that going back to that model is not really good idea due to number of places where we need to do plumbing.

I'm not sure that there's fine way to check if image is there during first call.

Regarding poorly made images, that's not kinda true, for instance image with OpenCV 3.3, TensorFlow would be around 1Gb plus neural network model that takes at least the same size. (around. 2.5 to 3.6Gb in total)

**Comment by rdallman** [comment]
> As far as i remember, before agent we have dedicated timeout for pulling an image

previously, we weren't even starting the timeout until after pull, so it would wait around. issue there isn't plumbing, it's simply incorrect as we weren't obeying the timeout. 

> I'm not sure that there's fine way to check if image is there during first call.

it gets stuck pulling the image, but down below we could add a call to `inspect_image` in the docker api if we hit a timeout, and if it's not there then we can have a special error (context unclear in statement, if you want to clarify, maybe I'm not talking about the right thing). it may not be worth it, really. but we probably do need to differentiate 'safe-to-rerun' timeouts, i.e. the task never ran; whether that's because the image not there or any other reason.

> Regarding poorly made images, that's not kinda true,

sure, it's not always true. but many users use 'ubuntu' image and have massive images unnecessarily, often. that's not the point, the point is large images happen somewhat frequently for whatever reason, poor construction or necessity. anyway, missing the point.

**Comment by rdallman** [comment]
not sure how to implement this for a service and oss?
