### ISSUE TITLE
Discussion: for most places we have headers, make them single key/value rather than array

### ISSUE THREAD

**Issue by treeder** [fnproject/fn#459]
Headers found in:

* func.yaml
* JSON format
* API

All of these are taking an array of values, which is really annoying and probably for 99% of cases, it will never have more than one. I propose that we just have single key/value for headers in all these places to make it easier to work with. Multi-value could be done by the user if required by concatenating values together.

**Comment by rdallman** [comment]
the headers are very much a mess and we are making some unfortunate assumptions to coerce them into formats for various things (headers, env) -- for storage it makes sense to keep them as an array. for the API and maybe for the func.yaml we could probably accept both, rather than asking them to csv things (it would be easy to deserialize either an array or single value into an array, we can make a custom UnmarshalJSON for it). for JSON it makes sense to keep as an array imo. even though we're coercing the http body into a json body, the user could use request headers to encode things a certain way and typically clients offer up multiple options for this, and users could serve the body back under one of those encodings easily enough; there are likely similar cases for other popular http headers (lest we forget we're ultimately letting the user serve http requests here; power users will want stuff like this).

**Comment by denismakogon** [comment]
I tend to agree with @rdallman, headers are messy at this moment. So, we can allow CLI accept key-value (where value is of basic type - string, int, etc.). But at the API level I’d better leave them as is because we’d need to do a lot plumbing within Fn including protocols.

I’d the main concern here is how CLI looks, then is something that can be done in fast.

**Comment by treeder** [comment]
Is there any common use case to have an array of header values?

**Comment by zootalures** [comment]
The inbound  headers I'm aware of that are problematic are `Accept` and `Cookie`  - both can be canonicalised to a single header (via comma delim and semicolon delim respectively) on the inbound request. I am not aware of any inbound headers that can't be consolidated into a single header at the gateway (with some sensitivity as to how to do that)  although that will be user-problem-specific. 

Outbound IIRC `Set-cookie` needs to be duplicated - there are probably others though.  

From a taste/smell perspective:  My first thought was that dropping multiple header values feels like a bad idea   - I like the idea of thinking of functions as micro-http-services and not being able to support full HTTP would be a problem. 

That said, I see how this is potentially ambiguous/confusing and If I was going to pick an event metadata model from scratch I don't think I'd have multi-valued fields. 

----

So, for me it comes down to how closely you want to tie the event model to HTTP  and whether the current http gateway is the primary way we connect outward facing HTTP to functions - @treeder  do you have a long-term view on how this pans out? 

Assuming that serving HTTP faithfully is an ongoing goal, I can see two general paths here:  

1) Fn routes stay HTTP native, functions behave as lightweight HTTP services being served natively within the platform. 

This is how it works for now, in this case I think its better to preserve http semantics as best we can within the Fn event model, including multi-valued headers.  

The cold contract is problematic and has the same properties as CGI in this case (hard to support duplicated headers, issues with clashing headers after canonicalisation) - I think that's mitigated by the fact that if you are serving http you are more likely to use a hot format than cold so you can keep cold for one-shot workloads and keep headers transparent for hot workloads.   CGI also sets out some (Ok, not super-simple) conventions for dealing with duplicate headers going into a single key in env. 

2) Outward facing HTTP events are independent from, but encapsulated within and are separate from underlying the Fn event model 

e.g. : 

```
[http call] -> HTTP Gateway/LB -> [Fn event [http event]] -> Fn -> Function 
```

I think if we look outwards (to e.g. how to handle general events on queues) this might be the direction we have to take anyway - i.e. the Fn events diverge away from http sufficiently to warrant wrapping HTTP events.  - that might be preferable to trying to fit all other (e.g. reading IOT events from kafka) event models within HTTP.

**Comment by treeder** [comment]
Your 2 is spot on, IMO, and the way I'd like to go. I've been really trying to avoid having anything HTTP specific (I know a lot has creeped in anyways) so that we can reuse functions with any type of transport. Tying it to HTTP prevents any future transports (kafka, grpc, etc). 

There are some cases that have been brought up where an advanced user might want to take advantage of HTTP, but I'd like that to be a very explicit thing, knowing that that function is bound to HTTP forever (eg: writing directly to the response stream or setting cookies).

In my view, like everything else we've done so far, the default should be very simple and not have any transport specific items. If the developer needs more, we can provide ways to gain access to transport specific things, but it should be frowned upon for the most part. 

And we're not alone here, the [OpenEvents spec](https://github.com/cncf/wg-serverless/tree/master/proposals/open-events) which we will support has no HTTP specific items in it. Obviously some things can be pulled out of HTTP like `dataContentType`, but the function writer gets nothing that is HTTP specific.

**Comment by treeder** [comment]
#476 may change how we think about these things.

**Comment by treeder** [comment]
Going to close this, assuming we won't change the header arrays.
