### ISSUE TITLE
Add support for full offline mode

### ISSUE THREAD

**Issue by brunoborges** [fnproject/fn#462]
To develop locally with Fn, one must have internet connection due to the hard dependency with Docker Hub as per README.md: 

```
# Set your Docker Hub username
export FN_REGISTRY=<DOCKERHUB_USERNAME>
```

It is crucial to allow developers to work on offline mode for many reasons.

Would be nice to have a feature like:

```
fn start --go-offline
```

This call would download all available FDKs and latest Docker images.

**Comment by treeder** [comment]
If you've run `fn start` once already, then you can work offline. `fn deploy --local` keeps deploys local too.

**Comment by brunoborges** [comment]
Maybe having ```fn start --local``` would make more sense, and then any ```fn deploy``` would automatically attempt local initially (with pretty fast timeout) and then remote. Having to do --local on every fn deploy seems odd.

**Comment by carimura** [comment]
`fn start` simply starts the server. I don't think it makes sense for the server to have an offline mode. That said the confusion might be because `fn deploy` is doing both a build and a push, whereas --local skips the push. Can think about this one but more urgent work to be done.

**Comment by rdallman** [comment]
I have not had any issues doing development offline (damn you, sightglass!), for what it's worth. That being said, it's because I have all the images downloaded from working online previously. One test fails, but as far as building the `fn` image itself and using the cli, with `fn deploy --local` it has been pretty painless to work offline. Big +1 for airplane mode working tho, a good thing to keep in mind :)

a list of images:

* `fnproject/functions` (this can be easily built with `make docker-build`)
* `mysql`
* `postgres`
* `fnproject/hello`
* `fnproject/error`

possibly others (mostly underneath the above images, i believe), but running `make test` while online will get most stuff necessary for dev; i.e. it's close to the desired `fn start --go-offline`, fdk's are a notable exclusion.

**Comment by denismakogon** [comment]
I can only add that you might need following images for development/testing:
 - `redis`
 -  `quay.io/goswagger/swagger`
 -  `funcy/timeout:0.0.1`
 -  `funcy/multi-log:0.0.1`
 -  `denismakogon/os.environ`
 - `funcy/log:0.0.1`

Regarding FDKs, AFAIK we don't have images for each of supported. We insist on to use programming language-specific distribution/consumption model (wheels for python, gem for ruby, etc.)

@treeder can we move those (from mine and funcy spaces) images to `fnproject` space?

**Comment by treeder** [comment]
Closing since this already works.
