### ISSUE TITLE
Swarm link broken in docs

### ISSUE THREAD

**Issue by treeder** [fnproject/fn#471]
https://github.com/fnproject/fn/blob/master/docs/README.md

**Comment by derekschultz** [comment]
I was updating the K8s docs (https://github.com/fnproject/fn/pull/372) just prior to the OSS release and had removed the Swarm doc in this commit: https://github.com/fnproject/fn/commit/2f090d0aab7c1cf9add6d3b640495507de814ed7

Mostly because I didn't have enough time to do both, and I haven't used Swarm in over a year, so was unsure whether or not it was even going to work as stated in the doc. Docker also recently announced they are adding native Kubernetes support, meaning it'll support both Swarm and K8s as the orchestrator, but IMO I see Swarm as more of a headache with an uncertain future.

Not saying we shouldn't have a Swarm doc, just need to come back to it and re-do the doc, making it simple.

**Comment by treeder** [comment]
Ok, how about just remove the link then and we can add back if/when we make a swarm doc.

**Comment by derekschultz** [comment]
Sure thing, https://github.com/fnproject/fn/pull/474

**Comment by derekschultz** [comment]
closing as #474 was merged
