### ISSUE TITLE
FDK Contexts

### ISSUE THREAD

**Issue by treeder** [fnproject/fn#476]
Per our group discussion about FDK's, just want to define what we put in our Context objects in the FDK's .

* ctx.CallID() string
* ctx.ContentType() string
* ctx.Config() map[string]string - app + route configs merged
* ctx.Get(string) - returns arbitrary object - this is where things like HTTP headers map would go, eg: ctx.Get("headers") => map[string][]string

**Comment by rdallman** [comment]
`ctx.Get()` has confusing functionality since it's not clear whether it returns things from the config or the headers (or both), comments won't really fix that. if we return from both that seems fine, `ctx.Get("headers") => map[string][]string` seems hairy, because a user could make a config key that is "headers". 

`ctx.Config()` and `ctx.Headers()` seems sane, with `ctx.Get(string)` pulling from either one potentially, but the precedence is tricky.

**Comment by treeder** [comment]
It returns from neither, `ctx.Get("headers")` returns the headers map. `ctx.Get("whatever")` would return something else, perhaps from another transport. A config key that is called headers would not conflict because config is already in `ctx.Config()`. If it were in `Get()`, it would be used like so: `ctx.Get("config")[string]`

**Comment by denismakogon** [comment]
I agree with Reed. We'd better go with the separate method for each type of protocol-specific mandatory fields. So, `context.Headers()` style is more preferable.

I know that headers, app/route config are the things we don't like to change. But can we somehow distinguish app config and route config inside function's runtime?

One more field to add to the list of things @treeder described:
 - `context.Format()`
 - `context.App()`
 - `context.Route()`
 - `context.ContentLength()` (in http we have exact header to use, but we don't have that in JSON

**Comment by hhexo** [comment]
My 2 cents / pennies / eurocents...

I agree with Reed and Denis, a `get(string)` is too vaguely defined, and also not very idiomatic in more type-safe or opinionated languages where I would actually expect at least a `get(some kind of enum)` or even a genercized `get<T>()` where T is a type parameter denoting what we want to get. However, I disagree that we should expose different methods for each transport protocol and thus expose the protocols and require the developer to know which one was used (or get all of them until they get a non-null result).

In fact, I would even venture the idea that we should not specify too much the actual methods to get the data (which could and look different in every language), but we should specify what data is available and what it means. In other words, in this situation we can't yet specify "what the FDK should look like" because we still haven't really specified "what is the data that Fn can provide to the function".

My personal opinion is that the data is clearly differentiated based on _who_ provides it, but the _how_ it is provided doesn't matter too much to the function developer: it could be http / kafka / whatever is used to call the function. So it seems to me that a function developer would essentially care about four types of data to handle in their function:

- Entirely contract-based Fn-specific values (call id, format, etc - provided by the Fn infrastructure)
- Key/Value pairs from configuration (provided by the function developer / maintainer / operator)
- Accessory Key/Value pairs from user input (provided by the caller via http headers or in the event)
- A body of raw user input content (provided by the caller via http body or in the event)

Content type and length are a bit of a special case because we need to know them to interpret the body, so I'm not sure where exactly they would fit (I would consider them first-class Fn-specific stuff but that's just my gut feeling); still, it seems to me that everything else falls into one of those four categories.

It follows then that the "specification" I would suggest is that a "context representation" (again, it could be different in every language as long as it is still referred to as "the context") should have:

- Individual accessors to get Fn-specific stuff (e.g. a `ctx.callID()` method - just an example in one language, not a spec)
- A single accessor to access the key/value pairs in the config (for example as a method returning a read-only reference to a map, dict, or whatever the language allows)
- A single accessor to access the key/value pairs in the user input (for example as a method returning a read-only reference to a map, dict, or whatever the language allows)
- A single accessor to the raw body stream (or maybe we can omit this and say that the body stream will always be in the "input" parameter to the handler)

Incidentally, if we separate the data by who provides it, we then give the function developer all the information to decide things like precedence of user input vs config. We don't want to dictate that decision in our framework, because each developer might have their own rules based on business logic (e.g. to handle configurable defaults).

**Comment by treeder** [comment]
Responding to @denismakogon 's comment:

* Format: is that useful to the function writer?  What would they do with that information?
* App/Route: +1
* ContentLength: if they did need it, they could just check the length on the `input`. If we support a streaming input option, I guess that would be more useful, but the common case won't be streaming (ie: most likely came in JSON format).

**Comment by treeder** [comment]
Responding to @hhexo 's comment:

Regarding the input we provide to the function, it's somewhat defined already and pretty much covers all 4 of your suggestions (docs could be a lot better, but I think it's sort of influx due to [this](https://github.com/fnproject/fn/pull/370). Both default and http format include 1 and 2 in the environment, 3 is in the environment for default format and in the http headers for http format. 4 is through STDIN. 

You might want to get in on this conversation about the JSON input as we're trying to define it: https://github.com/fnproject/fn/pull/463 (and I'm thinking the JSON format should relate to the discussion we're having here). 

Regarding the "context specification":

I think your 1, 2 and 4 are already covered and based on yours and others input, there appears to be some agreement on those. 4 is the separate `input` parameter though, not part of the context. 3 is the one we're mostly discussing here. 

> A single accessor to access the key/value pairs in the user input (for example as a method returning a read-only reference to a map, dict, or whatever the language allows)

Are you suggesting something like `ctx.Arguments()`? That returns some sort of map based on whatever the input is, defined by transport? That's not a bad idea, makes sense. But what is an argument in an HTTP request?  All the headers?  The query params?  Some parts of the path?  If we take all of those and put them into the same map, would it be confusing?  I think query parameters are an obvious one, you'd almost always want those (currently accessible via `request_url`). Parts of a path would be useful/required, especially if dynamic, but we haven't solved for that yet. I would venture a guess that the main header people would want to get access to is `Authorization` (we already provide content-type), and maybe that becomes top-level accessor (as discussed in meeting). Also, a lot (vast majority?) of user input will be JSON which will be a primary source of arguments to a function. 

I think there's something there, but maybe we should flesh it out along with some real world examples.

**Comment by denismakogon** [comment]
@treeder so, having content length as part of format would let FDKs (at least Python, maybe others) provide body (from JSON object) as streaming object so there would be no need to keep fully in memory rather than providing streamable objects (similar to what @jan-g did for HTTP format, we provide input as content length stream reader).

**Comment by denismakogon** [comment]
So, here's one question. Where should protocol-specific attributes be stored?
For HTTP protocol we have following fields:
 - HTTP method
 - request URL
 - query parameters
 - HTTP proto version

Simple solution would be to put them inside `context.protocol` object. @treeder @rdallman @zootalures @hhexo thoughts?

**Comment by hhexo** [comment]
I was indeed suggesting something like `ctx.Arguments()`. We would then need to define a contract for how protocol-specific differences are handled when collating the data.

@treeder has a very good point about the different types of key/value pairs in an http request... we have headers, query params, and other stuff (@denismakogon mentioned url, method and version), all can be possibly represented as key/value. Arguably it's http's fault for being a bit disorganized with its input - but it's true that http features solve different problems than the ones we have. :)

To have our cake and eat it, we could have two different APIs: we have an abstraction ("the context") as the default or recommended / documented way of working, and if you want to go low-level you use a different API and get the raw protocol data structures.

If the APIs are different, then we don't have to compromise, so we can say that the "context" is only our abstraction and we entirely dictate what goes in it (as long as we document the contract) regardless of protocol. `InputEvent` in the Java FDK is already quite close to this idea (minus the fact it exposes the headers).

**Comment by denismakogon** [comment]
Okay, I'm good with `context.Arguments()` as key-value. Just wanted to make things clear. It looks like JSON protocol has nothing like HTTP, no version, no query parameters, etc. So that just might be empty, anyway, let's stick with the following API (bare minimum) for context object:
```
CallID() // Fn call ID
AppName() // Fn app name
Route() // Fn app route path
Config() // Fn app and/or route key-value config
Headers() // Call request headers
Arguments() // for protocol-specific attributes
```

Questions:
1. Should we include `context.RequestURL()` as well? For hot JSON/HTTP it always dynamic and developers might want to access/use it.

**Comment by rdallman** [comment]
> Should we include context.RequestURL() as well? For hot JSON/HTTP it always dynamic and developers might want to access/use it.

it's possible we have non-http input in the future, so it may be best to leave this tucked away in the headers for the time being.

**Comment by denismakogon** [comment]
I do remember that we at least talked about that, agree, that still possible. But I don't remember that we talked about having non-http function triggering. I mean, we'd still have http requests used for triggering function, no?

**Comment by rdallman** [comment]
not necessarily I don't think. for example, we could consume a kafka topic directly and generate 'functions' from that (i.e. the topic name is the "route" to use, with each message a payload [of some possible format])

**Comment by denismakogon** [comment]
Okay, if the call will go in a different path, then agree, request URL should stay somewhere behind the scene and be available through HTTP headers.

**Comment by treeder** [comment]
I don't think we all agree on headers either, I don't think it should be a top level method. The following so far are for sure, the rest we should stick in an arbitrary map until we figure out where (or if) we want them top level. 

```
CallID() // Fn call ID
ContentType() // eg: application/json
AppName() // Fn app name
Route() // Fn app route path
Config() // Fn app and/or route key-value config
SomeFunctionToGetOtherArbitraryValuesOutOfAMap() // eg: Get("headers"), OpenEvents has an "attributes" map for extras like this btw. 
```

The reason that last function should be a map is to keep it flexible so we can put whatever we want into it until we decide whether something should get bumped up to the top. It could container "headers", "request_url", "query_parameters", "hostname", "container_id", etc. And we can safely move forward covering everything we need without locking ourselves into something.

**Comment by denismakogon** [comment]
Okay, so, OpenEvents appears pretty often, can't we implement JSON protocol according to OpenEvents spec? This looks more and more reasonable at this point. Of course, that would be OpenEvents-compatible JSON protocol, because we have more terms and resources than OpenEvents spec or we name things differently. Thoughts? @rdallman @treeder

**Comment by denismakogon** [comment]
`fdk-python` - done fully implements FDK Context spec.

**Comment by treeder** [comment]
Going to close this, seems we have some differing opinions so we'll leave it up to the FDK. 

The JSON input format essentially defines how this should look. The Ruby FDK is an example that translates from the JSON input into the context almost exactly.
