### ISSUE TITLE
Hot sync function: 504 from fn whilst the container still runs.

### ISSUE THREAD

**Issue by jan-g** [fnproject/fn#497]
I'm seeing the following behaviour from fn. (The run is triggered by flow but the behaviour's the same for functions called directly by the user.)

In this case the function makes a bunch of API calls over a period of (over) two minutes, before finally emitting a small amount of data. After two minutes, fn responds with a 504 timeout. However, I'm still seeing indications that the container continues to run after that 504 is received.

In my opinion (which I invite discussion on) this is error-prone: in this case, fn should probably stop the container (since it doesn't know if the function's run away or not) strictly *before* returning a 504. It's much harder to write correct software as a set of functions if I can't tell whether a timed-out function is going to attempt to trigger more side-effects after fn has returned to me.

Example log extract follows.

Function triggered (this log trace from flow service):

```
time="2017-11-10T12:04:40Z" level=info msg="Running Stage" faas_url="http://fn-service.fn:8080/r" function_id=t/flow-load-test-vista graph_id=6cd61dfb-2e88-47d6-9a9d-d441cca284c0 logger=executor_actor operation=thenCompose stage_id=2 
```

It generates some POSTs to the flow api:

```
[GIN] 2017/11/10 - 12:04:40 | 200 |  5.912722207s |      10.99.57.0 | POST     /graph/6cd61dfb-2e88-47d6-9a9d-d441cca284c0/stage/1/thenCompose
... about 20 lines elided ...
[GIN] 2017/11/10 - 12:05:55 | 200 |  1.776090655s |      10.99.57.0 | POST     /graph/6cd61dfb-2e88-47d6-9a9d-d441cca284c0/stage/28/thenApply
```

Then Fn gives up on the stage ever returning anything (timeout at 2 minutes):

```
time="2017-11-10T12:06:43Z" level=info msg="Fn load balancer delay" faas_url="http://fn-service.fn:8080/r" fn_lb_delay="81.197µs" function_id=t/flow-load-test-vista graph_id=6cd61dfb-2e88-47d6-9a9d-d441cca284c0 logger=executor_actor operation=thenCompose stage_id=2 
time="2017-11-10T12:06:43Z" level=error msg="Got non-200 error from FaaS endpoint" faas_url="http://fn-service.fn:8080/r" function_id=t/flow-load-test-vista graph_id=6cd61dfb-2e88-47d6-9a9d-d441cca284c0 http_status=504 logger=executor_actor operation=thenCompose stage_id=2 
```

However the container is not yet cancelled and is still running, which is where this comes from half-a-dozen seconds later:

```
[GIN] 2017/11/10 - 12:06:49 | 400 |   14.671578ms |      10.99.57.0 | POST     /graph/6cd61dfb-2e88-47d6-9a9d-d441cca284c0/stage/29/thenCompose
```

**Comment by rdallman** [comment]
there is a bug filed about swapping out the input/output pipes to avoid some of the possible confusion around these kinds of timeouts. for hot functions, ideally we leave the container up (not sure if this bug is filed in a hot or cold function context) and just swap out the output pipe to effectively shut that call down and free it up for another. in this case, it's true that the code in the container is likely still executing and not prepared to take more input, though fn will see it as available and attempt to shove more input into a container. for this reason, I think it's probably best we do something like https://github.com/fnproject/fn/issues/373 -- it's kind of hard for us to know whether a container is actually prepared to take input or not, there may also be some kind of trickery we could do with docker health checks https://github.com/fnproject/fn/pull/434 but this also seems like it would be something the client / us would have to inject into containers. anyway, it seems like if we shove deadline in that containers could effectively time out operations and cancel whatever it is they were doing to go take input for the next task. does #373 seem reasonable? would be concerned about container churn if we made all timed out hot tasks have to shut down the container (e.g. if user has 1s timeout and their db is fucked but they continue to send us 1000 rps...)

in the cold context, this should kind of fall out except for the docker remove command can take an inordinate amount of time [which leads me to believe this issue is filed about hot, so not expanding].

**Comment by jan-g** [comment]
The issue arose in a (very) loaded fn cluster: cf. Dario's comments about cpu saturation. In this instance it arose because a function had "plenty" of time to execute (2 min, usually runs in about 10s) but was hugely cpu-contended; under such a situation there's not a lot the function can do cooperatively to manage this. Could potentially rig up a signal internally with a view to aelf-destruction if the deadline were exceeded; that's still racy in many cases depending on the thread to whichthe signal is dispatched. I'll experiment along those lines.

-- Excuse typos. Phone screens don't make great ketbroads. 

-------- Original message --------

**Comment by rdallman** [comment]
thanks for context. perhaps in addition to memory we should check on cpu usage before allowing more calls to run on a given host to try to avoid these kind of contention issues, they are somewhat endemic and we've dealt with it in the past by simply reducing the number of concurrent tasks that could run on any host but `fn` is more dynamic than the product I'm speaking about.

**Comment by skinowski** [comment]
FYI: https://github.com/fnproject/fn/issues/509

**Comment by skinowski** [comment]
@jan-g could you post a brief explanation of the setup as well? How many fn servers, fn-lb instances?

**Comment by jan-g** [comment]
Using 8 VM.DenseIO1.4 nodes with /var/lib/docker on nvme for the DaemonSet.
Each node saw roughly the same proportion of "slow-function",
"fast-function" and "vista" containers on it (the latter c. 300 per node).
The issue here is that we've c. 63GB per node and yet "only" 8 cores, so Fn
packs these far too densely and they don't get much of a look-in.

We were really looking to capacity-test the Flow service; we just noticed
this en passant. We ended up replacing the Fn + functions part with a
golang "mock" based on GIN to get the capacity so that the Fn setup itself
didn't need scaling beyond belief to get numbers for a different part of
the system. However, in practice the "vista" test looks to put a reasonable
amount of - hopefully fairly realistic - stress on a system. (Note that the
"slow-function" in that represents the image processing steps; it's
replaced by a sleep since we were interested in the Flow side rather than
the Fn side, but if that was also number-crunching then the situation would
be rather exacerbated.) Clearly "your work demand exceeds your capacity" is
always going to be a problem that needs addressing; but Fn could definitely
be a bit smarter about allocating capacity for small, CPU-intensive
workloads.

**Comment by skinowski** [comment]
Should we close this? There were a few changes in since this was opened. Does #405 provide solution to this workload?

**Comment by jan-g** [comment]
I'll check this when I'm back in the office.

**Comment by skinowski** [comment]
Possibly related: #690

**Comment by rdallman** [comment]
i believe this is fixed as we're now shutting down containers if they exceed the timeout. re-open if i'm misinterpreting
