### ISSUE TITLE
Write timestamps to each log message produced by function

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#536]
Would be nice to have an ability to track log messages with timestamps. Each log message will have the following format:
`{timestamp in RFC 3339} - {call_id}: <log message>`

This should be done on Fn side because there's a chance that running function doesn't use FDK.

Not sure if it's good to reference other functions platforms, but GCP does the same:
![](https://cloud.google.com/functions/img/qs-log-history.png)

Also, as certain UX improvement would be nice to see exact execution time in addition to call timestamps (create|started|completed_at)

**Comment by rdallman** [comment]
it's possible to do this in a couple ways. 

one way, like docker does, is to have a list of lines for the log, each with tags and a timestamp. this gives more flexibility and doesn't pollute the logs with stuff we're injecting, which can be useful if a user is running the same code in 2 different contexts and doing matching against log lines, since we'd be changing the format of the logs. e.g.

```json
{"timestamp":"01:23:45Z", "tag":"some-tag", "log":"this is the log as it was logged"}
```

the other way is to inject it into the logs, which will be more efficient, but the trade off is that we're mutating users logs wrt formatting and some people might not like this. the syslog api will have to adhere to this anyway, it's just a matter of if we want to do this to the logs we are storing also. 

> Also, as certain UX improvement would be nice to see exact execution time in addition to call timestamps

this is really easy to calculate and any ui tool we have can show this easily, or even the cli tool. i think our primary interface point will be a ui or client bindings, client bindings can do this calculation easily too. saves ~25 byte every call on a redundant timestamp (run_time); queued time can be calculated also with the timestamps we already have, same deal, it's just redundant/wasteful.

**Comment by rdallman** [comment]
docker update seems to prepend timestamp onto every log line:

my docker version:

```
fn(user-syslog) ✗: docker version
Client:
 Version:       18.04.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    3d479c0
 Built: Tue Apr 10 18:21:29 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.04.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   3d479c0
  Built:        Tue Apr 10 18:19:37 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

example log from a call using that version of docker:

```
 ✗: curl -sSL localhost:8080/v1/apps/sup/calls/01CCD4MEKQ180043RZJ0000001/log
{"message":"Successfully loaded log","log":{"call_id":"01CCD4MEKQ180043RZJ0000001","log":"2018/05/01 06:01:02 wassup\n"}}
```

I'm about unsure of how I feel about docker changing the log format, but it does seem to solve most of this. in our current API, adding call id to every log line seems like it's pretty redundant since logs are addressed by call id (a ui could add this at display time if we _really_ wanted). for #337 i found this out, and it's really annoying since it's not in the right place for syslog format, which has RFC3339 as part of the spec, so am thinking about stripping it for that since the timestamp is in 2 places (but in a previous life, it was like this too for deployed services, log lines had timestamps in logfmt format, and also in syslog format).

at least, this issue seems resolved once we're all on docker > 18 ? (unless they change it again)

**Comment by rdallman** [comment]
one obvious issue is that the timestamp docker injects looks like it's localized time. boo.

**Comment by rdallman** [comment]
ya know what, this is cuz i used the `log` package. ignore me. nuking

**Comment by rdallman** [comment]
~related #970 we could use that format for all of our logs if we want, it looks like the same format as what gcp uses. gcp looks like it has auditing in the logs too. at least, if we used the syslog format we could have the UI parse and display it kinda pretty. there's also a chance we hook up all this to a logging service anyway instead of having our own log api (and we'd need a story for OSS there that's better than s3 probably).

**Comment by rdallman** [comment]
we're only allowing syslog logs now really, which handles this
