### ISSUE TITLE
research: http://opencensus.io/

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#695]
this looks like a promising project (from Google) largely based on opentracing's foundations, which has additional interfaces for normal things like gauges and counters, etc. at present we have our own little special way of doing these kinds of metrics in opentracing, but it seems like opencensus has all the sugar that opentracing has and more (clients for every lang, zipkin/jaeger support, standard interface with pluggable backends). out of the box they support a prometheus backend and a zipkin backend for the go one: https://github.com/census-instrumentation/opencensus-go

i think it would be pretty easy to swap out for with opentracing, from the looks of it. it seems like this would solve some of our headaches munging data from opentracing/openzipkin into prometheus.

**Comment by rdallman** [comment]
@nigeldeakin this is your wheelhouse, any thoughts on this?

**Comment by nigeldeakin** [comment]
Yes, it looks like a neutral API for tracing and metrics. 
The Go library is described as being "at a very early stage of development. The API is changing rapidly"

It looks a little early for me to want to jump in and start using it, 
at least whilst our existing mechanism continues to do what we want it to do. . 

Feature | Our way | Open Census
------------ | ------------- | -------------
API for tracing spans, independent of tracing backend | Yes, we use OpenTracing.<br><br> Currently Fn only allows Zipkin to be used. Switching to (say) Jaeger would be simple for tracing spans, but to keep the other features (below) working would require writing a new collector (since OpenTracing doesn't standardise the collector API). | Yes. OpenZipkin [is the only one mentioned](https://github.com/census-instrumentation/opencensus-go/blob/master/README.md) but supporting others is clearly a goal for the future.
Automatic conversion of span durations to duration histogram metrics | Yes, this is achieved using a custom Zipkin collector.<br><br> If we switched to a different trace back-end we would need to write a new collector (since OpenTracing doesn't standardise the collector API), unless Open Tracing allows two trace backends to be used at the same time | No, as far as I can see. 
API for metrics, independent of metrics system | Yes, there's an independent API, though it only works with Prometheus. Supporting a different metrics system would require changes to the custom Zipkin collector.<br><br>We currently use OpenTracing "observations" as the API for metrics, which is slightly contrived as it requires the creation of a span purely for the purpose of holding observations. This could be simplified by inventing our own API. | Yes. Prometheus [is the only one mentioned](https://github.com/census-instrumentation/opencensus-go/blob/master/README.md) but supporting others is clearly a goal for the future.

**Comment by rdallman** [comment]
> Automatic conversion of span durations to duration histogram metrics ... No, as far as I can see.

https://godoc.org/go.opencensus.io/trace#hdr-Enabling_Tracing_for_a_Program ? there is a prometheus exporter implementation in their repo which does not appear to currently implement `ExportSpan` but I can't imagine it would be hard to add, and it looks nice and easy to compose which exporters we want for various things. looking into this.

this really seems like the right path forward if only for an open api for metrics, it seems to encompass every feature we're using from open tracing at the moment with a bonus standardized wire format. I do agree it's early and we might get cut occasionally being on the bleeding edge. it does ultimately seem like it will be easier to go with it early on than trying to convert the beast later, and i'd think that their being 1.0 at least we'll get some compat guarantees even if we have to make minor tweaks to stay up to date with them code-wise. thanks for the detailed write up. 

have begun analyzing the surface area for this and hopefully coming up with something later this week.
