### ISSUE TITLE
Make the function timeout less affected by Fn operations and more meaningful for the user

### ISSUE THREAD

**Issue by hhexo** [fnproject/fn#723]
At the moment, the function timeout is used to determine when a function should be stopped if it overruns. My understanding is that the semantics work this way:

- For sync, the clock starts ticking when we receive the request
- For async, the clock starts ticking when we dequeue the call to run

The clock is therefore ticking when all the "start" operations are performed: find a slot (which can take a long time if the container image has to be downloaded and started) and update the database to set the call as "running".

The function developer has no control on how long Fn takes to do these operations. Therefore, they have to allow some "wriggle room" in their function timeout. Will an additional second be enough? Two? Five?

If the function developer hasn't allowed for enough wriggle room, the function user will occasionally see those nasty 503 "server too busy" errors which can currently happen because the deadline is exceeded before Fn has even managed to find a slot to run the function.

I personally think the clock should start ticking at least after a slot is found, i.e. the container is started. This way the meaning of the function timeout set by the developer is clear: my _code_ runs for at most X seconds, regardless of how long Fn takes.

**Comment by treeder** [comment]
Agree, the function should get the full timeout length to run. 

Regarding using a timestamp to say how long it has (continued from #662), can we be sure the clock inside the container is the same as the one on the host?  What if we get into freezing containers, that would probably make that explicit timestamp very wrong.

**Comment by skinowski** [comment]
We probably need two timeouts:

1) how long a function gets to run
2) the deadline to start executing a call

if 2 is not set, we could default it to 1 minute for sync calls.

For async calls, perhaps same deadline could be used to specify how long a request can sit in MQ and we could default that to whatever retention is provided in the MQ service.

Without clearly defining these, we'll have to answer questions like:

"my timeout is 5 secs, why did it take 2 minutes to run my func?"

or (today's situation):

"my timeout is 5 secs, why did my func actually got 2 secs?"

**Comment by skinowski** [comment]
Also, if say we had two timeouts; wait timeout and exec timeout as I suggested, we may have better retry policy it at lb level going forward...

For example, if wait timeout is set to say 60 secs and exec timeout of 5 secs, we could fail faster on fn servers and leave room for x number of retries at lb level... eg. "wait_timeout=60 exec_timeout=5 retries=2" could be a policy of 30 secs on each fn server.

**Comment by skinowski** [comment]
Another idea is to perhaps make this second timeout as a system wide config, eg. x minutes, where
we can queue, wait for docker pull, etc. up to x minutes, but still give the function the timeout
specified in the route config.

**Comment by rdallman** [comment]
also wrt lb, for sync we're going to impose lb timeout limits on the request as well, which will provide cancellation if e.g. image pulling takes too long; not sure we can rely on this exactly so we should have additional measures. for async, we could inject the same timeout or do something else.

**Comment by skinowski** [comment]
maybe we can come up with a scheme like;

x = timeout for route (configured by users)
y = fn server system side queue/pull timeout (eg. 1 min)
z = fnlb timeout (eg. x + y + 10 secs)
r = fnlb max retries (eg. 3)

1) fnlb with a retry max setting (r) (eg. try 3 times) which means try next fn server in the ring.
2) fnlb with a sentinel max timeout (z) per request, to catch dead/hung conns.
3) each fn server with system wide timeout (y) for queue/pull: eg. 1 minute
4) customers always get the "timeout" (x) they configured inside their containers

With this, it would mean fnlb can retry and spend up to (z * r) minutes, but passively based on fn server responses. Only if fn responds with 503 (or tcp connect failure), then fnlb can retry next, otherwise we risk not being idempotent. And going forward, we can try to make fn server smarter and fail it faster with 503 to let fnlb try next quicker.

For async, we can dequeue and use perhaps the same y timeout for queue/pull. And if it times out, we
retry (or not commit to allow other fn nodes to pick) Or perhaps, we dequeue, then submit it through frontdoor as sync to decrease error rates and let fnlb work it's retry logic on the fleet.

fnlb can auto configure z and/or r based on /version if we add these in /version output if keeping fnlb and fn server settings is a problem.

**Comment by skinowski** [comment]
I'd like to move forward with this with the following proposal:

1) redefine existing timeout as 'approximate amount of time a function gets in a container'
2) introduce a per-route schedulerTimeout as the amount of time scheduler (LB or agent) can spend
to wait for resources to place/retry a call.

schedulerTimeout if not specified by the customer can default to either:

a) %50 of timeout
b) minimum of (10 secs, timeout)

where we'd cap max schedulerTimeout based on a system wide setting (eg. 300 secs) if an env var is configured.

In this model, customers will get somewhat predictable timeout in their functions. And they should
expect front-door http client total wait time of "schedulerTimeout + timeout".

**Comment by skinowski** [comment]
cc @mantree

**Comment by skinowski** [comment]
cc @kmjohansen

**Comment by mantree** [comment]
Sounds good to me.

**Comment by skinowski** [comment]
After offline discussions today, we are proposing the following:

Retain & keep existing per-route setting 'timeout' as is, however it's definition changes to "maximum amount of time a function may execute in a container".

Total request wait time is expected to be implicitly handled by http-client. We will let http-client
wait as long as it can tolerate(*).

In other words, we bound the execution time inside the container using the existing 'timeout'
parameter, but let the http-client wait for scheduling delays plus execution. Scheduling can be
delayed due to LB retries, docker-pull, docker-start, runner/agent slot wait, waiting for cpu & memory,
etc.

(*) Maximum time for the client to wait will/should be imposed by LB or other API gateway
production service settings. (eg. LB http.server imposed timeouts.)

**Comment by rdallman** [comment]
not opposed at all, just an additional point to consider is the 50% thing is mostly nice for async, with it going away async will get a lot more 'timeout' status if node(s) have many functions queued up. thinking about it, no obvious fix sticks out since slots aren't plumbed out (even if there's capacity, there's still docker pull to eat the clock...). maybe something comes to mind for someone else.

**Comment by skinowski** [comment]
PR active: #1021

**Comment by skinowski** [comment]
Closing this due to #1021
