### ISSUE TITLE
Big load test

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#80]
In gitlab by @treeder on Jun 20, 2017, 14:59

Run millions of functions and track timings, error rates, etc.

**Comment by rdallman** [comment]
I think @hhexo and co. are doing this for flow, we can likely reuse the framework at least? I can think of numerous bugs we'll run into but the server isn't really polished wrt the api so that seems more important...

**Comment by hhexo** [comment]
We currently have an ad-hoc framework that we're still working on, see https://github.com/fnproject/flow-load-testing - it's a private repo but you should have access, I think.

One of the problems we're having is to figure out what a "representative" load for flow is (how is a typical graph structured), however you probably don't have that problem for general functions - you just run tons of them.

I imagine that for hot functions, once you saturate the container space (N containers per node where N = memory / (memory per container) ), your parallelism will be maxed out so you should be able to easily estimate what the results of a test should be, and detect any difference.

**Comment by jan-g** [comment]
We're still in the process of getting to the point where I can max out that
theoretical capacity of an fn cluster; for single flows we are still seeing
some kind of bug where the return message from the graph actor doesn't come
back to the REST api's Ask future. That's one distinct failure; the actual
ramp-up other wise looks okay although I am still getting to the point of
driving it hard enough to see an fn backlog build up.

**Comment by hhexo** [comment]
Yesterday I came up with some considerations after I hammered an Fn node trying to run functions to create many many Flows in a short time.

As far as I know (I may be wrong) Fn's policy for determining the number of concurrent containers is based on some function of memory. On a reasonably sized Fn node, I might have given 32GB of memory to Fn which means that, if each function is by default limited to 128MB, in theory I could run up to 256 concurrent function containers. I don't know if that theoretical limit is reached, but I have seen the number of containers reach at least 208 in my tests when I observed it, so let's go with the theory.
The problem here is that on the machine I might only have a small number of CPUs (say, 4CPUs which are actually 8 threads).

Assume that my function usually runs in 1 second, so I gave it a generous timeout of 30 seconds. Also assume that the scheduler is fair, and each container gets an equal share of the CPU time. In such a configuration of containers, that CPU share is 8 / 256 = 0.03125 "processors per container".
My function running in such a configuration would take on average (handwaving the fact that scheduling is quantized rather than continuous) 1 / 0.03125 = 32 seconds. It would then very likely time out before it's finished.
And this is without considering the overhead that Docker adds when starting a lot of containers. Anecdotally, Docker gets slower the more containers are alive.

I admit, I don't have precise numbers here, mostly because my focus was testing Flow rather than Fn. However, I worry that functions are actually CPU-bound, and I propose that one of the outcomes of load testing for Fn should be to find out how much that is a problem. 
I would recommend a test based on a function with a known deterministic single-threaded duration, measuring how "slower" it gets when more containers are around.
I think this would be very important feedback for Fn's scaling policy.

**Comment by rdallman** [comment]
@hhexo I agree that it's very likely for fn nodes to be cpu bound more so than memory bound, obviously dependent on workload but I think it's likely the normal case. I've made a comment https://github.com/fnproject/fn/issues/497#issuecomment-344333715 to do something about this. we _should_ be able to check this when trying to create a new slot (note: not existing slot that is free) and queue it or 504 so that the function could run elsewhere. does this seem like a good idea? as far as load testing, it would be great to save the cpu contended workload presented from the current tests and use it against a version of fn that attempts to apply back pressure when the cpu is saturated to see if things are faster / slower, this will give us an obvious path forward.

**Comment by rdallman** [comment]
this ticket isn't providing very much value and we have addressed the cpu concerns in #642 - I see multiple tracks here: benchmarking, CI-like load testing for verification, testing thresholds -- each of these useful in its own right -- if we break out and do any of those we can make separate, more specific tickets for them.

most people I've seen to date have been using a standard http benchmarking framework (they are vast) after setting up some routes and then watching for fireworks.
