### ISSUE TITLE
Should app removal stop all running functions or wait until they finish?

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#845]
Here's the quite interesting flow:
1. Create an app with routes.
2. Start a bunch of hot functions with >30secs idle timeout.
3. Delete the app.
4. Recreate the same app but with slightly modified config.

You'll notice that they are up and running and only newer functions will get a newer state(env, configuration, etc.)

So, here's kinda open question: should we forbid app delete procedure if it has running functions or should we schedule the deletion of the app once all of its functions paused/finished?

**Comment by rdallman** [comment]
it's going to be really hard to shut down all functions on a 1000 node cluster, and it's not really worth it. we also have a layer of caching. we have atomicity insofar as every function running was started when the app existed, and after the app is deleted new ones won't start (unless recreate under same name).

> You'll notice that they are up and running and only newer functions will get a newer state(env, configuration, etc.)

this is how it should work (once we have app id, it'll be correct)

anyway, imo not worth it. I think the idea expressed here is that it's weird to have 2 effectively different functions running under the same app name because of delete-then-recreate. once we have app id there's a really clear boundary here. let's fix that...

**Comment by denismakogon** [comment]
> it's going to be really hard to shut down all functions on a 1000 node cluster

yeah, it just feels different, from UX there would be no difference.

> this is how it should work (once we have app id, it'll be correct)

i know, just expressing that as a statement.

> once we have app id there's a really clear boundary here. let's fix that...

good point, we're on our way there.
