### ISSUE TITLE
Runner content detect is inconsistent for certain type of the JSON objects

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#867]
In runner, we [trying to identify](https://github.com/fnproject/fn/blob/master/api/server/runner.go#L121-L132) whether the function's response is a JSON object.
Unfortunately, it works only for very specific JSON objects that starts with `{`, but the JSON objects could be very different, here's at least one valid case of the JSON object:
```json
[
    {
        "a":"b"
    },
    {
        "a":"b"
    }
]
```

To solve this, we need to change the way we do the detection, here's a link to the solution i propose: https://play.golang.org/p/K6bw6eeeu9l

**Comment by rdallman** [comment]
At some point we have to say that the user has to set the content type to what they want, it's not realistic for users to rely on us to have perfect content type detection. This existing is mostly an artifact of some code sliding in to default to json content type when this is not even generally the case, and certain user routes relying on this behavior. It was a mistake to let that behavior in to begin with.

Doesn't seem like it's worth it to read an entire body into another byte slice simply so that we can check content type (as proposed), the stdlib detect only reads the first 500 bytes potentially but does no copying. If the opening bracket for a list does not conflict with any other content types, then we can consider adding that case. But a string or number are also valid json values and we can't detect that. It's worth reading the RFC since my words mean less than theirs: https://tools.ietf.org/html/rfc7231#section-3.1.1.5

In any event, strongly prefer encouraging users to set their content type, per the RFC reasoning.

**Comment by rdallman** [comment]
closing as 'expectations too lofty' with the +2
