### ISSUE TITLE
Clean up temp Dockerfile if fn command is interrupted

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#89]
In gitlab by @mhaji on Jun 27, 2017, 07:43

Currently, if I'm running `fn run` or `fn build` a temporary Dockerfile is created in the working directory. If the execution is interrupted, this file is not cleaned up. This can have unexpected behaviour as subsequent `fn run|build` commands will not generate a new temporary file Dockerfile and will continue to use the old one.

Suggestion is to register a sig handler/shutdown hook to clean this file up.

Might look at sending a PR for this if I can get to it, but I thought I would create the issue first.

**Comment by reclaro** [comment]
I did some tests and I was not able to reproduce the issue, plus I looked at the code and the signal is managed correctly (https://github.com/fnproject/cli/blob/master/common.go#L131) and we delete the temporary `Dockerfile` with `defer` https://github.com/fnproject/cli/blob/master/common.go#L107
To me the issue can be closed as fixed.
I don't understand why the bug is open against the `fn` project, in my understanding `build` and `run` are performed by the `cli`therefore I expected to see this as a `cli` issue, am I right?

**Comment by hhexo** [comment]
The cli used to be a sub-project in the `fn` repo, that's why this issue is not in `cli`... it is a very old issue. :)

Good to know it's fixed.

**Comment by rdallman** [comment]
have a sneaking suspicion our loitering issue has changed to leaving around intermediate build images instead of docker files now, but that's not quite this. thanks for investigating, I believe you cracked this one @reclaro
