### ISSUE TITLE
Fn API URL schema being modified during event dispatching

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#958]
## problem

Assume you have Fn running over HTTPs with ngrok: `https://0a1a3f0a.ngrok.io`
When trying to get Fn API URL using the following code:
```go
	fctx := fdk.Context(ctx)
	u, _ := url.Parse(fctx.RequestURL)
	fnAPIURL := fctx.RequestURL[:len(fctx.RequestURL)-len(u.EscapedPath())]
	log.Println("Fn API URL: ", fnAPIURL)
```
URL schema turns from HTTPs to HTTP

## steps to reproduce

1. Create Go function and add code mentioned above.
2. Call a function using Fn endpoint with HTTPs.
3. Check call logs

**Comment by rdallman** [comment]
does ngrok call fn with https? do we just need to check `X-Forwarded-For` for the original URL? I guess we will almost always front fn with an lb and want the original request url, we probably need to plumb that. but i don't think the bug is in http/https scheme solving. with cloud events the event uri is in there, maybe that's all we really need to do. gonna close but maybe we should open an issue for ^ ?
