### ISSUE TITLE
to run the aws lambda function

### ISSUE THREAD

**Issue by Littermonkey** [fnproject/fn#959]
I tried to run lambda functions by document .but I couldn't find the right runtime. 
so I want to run the aws lambda functions without any change. what should i do.  by the way ,my functions with python 2.7 .

**Comment by denismakogon** [comment]
Fn does not support python 2.7 at all (and would not). I recommend to make your function work with python 3.6 and use FDK-python to get proper integration.

**Comment by denismakogon** [comment]
If like I can guide you through on both: py3 migration and fn integration.

**Comment by Littermonkey** [comment]
I love the open source ,It's fascinating. but The code for my project is written in python 2.7. So, Can you give me some feasible suggestions? @denismakogon . thanks

**Comment by denismakogon** [comment]
First of all, I recommend to go through development docs: https://github.com/fnproject/fn/blob/master/docs/developers in order to get familiar with Fn and how it works along with best practices how to develop function, etc.

**Comment by Littermonkey** [comment]
”Import Lambda functions and run them anywhere“  but  I import lambda function from my aws server, It's doesn't work .can you tell me why?

**Comment by denismakogon** [comment]
@Littermonkey Would you mind to be more explicit please about what doesn't work?

**Comment by Littermonkey** [comment]
it is show have not right runtime . when I import lambda function runtime there's a limit?

**Comment by denismakogon** [comment]
Which runtime? Please provide more information, hard to guess what’s going on without an actual problem details.

Note that runtime means literally nothing to Fn server, it’s only for CLI since Fn works with containers, not the programming language runtime. For Fn container is the runtime, which is one of the best features we did.

**Comment by Littermonkey** [comment]
Ok, I will tell you what the specific requirements are, and I need to get the lambda function code to run on any cloud service without making any changes. but the lambda function runtime is python2.7. 
now ,How I to do ?

**Comment by denismakogon** [comment]
Import your function with Fn CLI and set runtime to `docker`.  Here’s the doc how to do so https://github.com/fnproject/fn/blob/master/docs/lambda/import.md
Before `fn deploy` update `runtime` in `func.yml`:
`runtime: docker`

**Comment by Littermonkey** [comment]
"""Bumped to version 0.0.3
ERROR: Dockerfile does not exist for 'docker' runtime""“
when I fn deploy ,The above error occurred.

**Comment by denismakogon** [comment]
Show me the content of your `func.yml`. Basically, you need to write a Dockerfile to package your code into a container.

**Comment by Littermonkey** [comment]
name: glb1223/test_hello
version: 0.0.3
runtime: docker
cmd: lambda_function.lambda_handler
path: /test_hello
~

**Comment by denismakogon** [comment]
So, yes, you need to write dockerfile to package your function into a container.

**Comment by Littermonkey** [comment]
ok ,  so Does func.yml need to change?

**Comment by denismakogon** [comment]
What do you mean? Just write dockerfile, put that near func.yml and call deploy.

**Comment by Littermonkey** [comment]
Thank you very much , I have a try.

**Comment by denismakogon** [comment]
Hi! Well, this is quite problematic question because of the of the complete difference between concepts of a function between Lambda and Fn. I guess, you are aware that Lambda has a wrapper that starts your function by dynamically loading your code to the runtime (that's why Lambda supported Node and Python as first programming languages to deliver).

Fn is totally different, the runtime for a function is not an actual programming language runtime but docker container, so Fn is not aware of your code, which signature it has and what it does. It means that you decide on the signature, but you are responsible for request data parsing from the protocol frame (in case of hot functions), that's why we made a bunch of FDKs for Node, Go, Python 3.6, Java, Ruby, Kotlin, etc.

I may be wrong, because i didn't try lambda import, however, i have pretty strong opinion that you can't import lambda function without actually changing your code to make it work with Fn.

cc @treeder

**Comment by Littermonkey** [comment]
Well, let me ask if there is a better way to run lambda function. please give me some advice.

**Comment by Littermonkey** [comment]
Well, let me ask if there is a better way to run lambda function. please give me some advice.

**Comment by denismakogon** [comment]
Unfortunately, have no idea at this moment except changing the code of your function.

**Comment by Littermonkey** [comment]
Change the function code , You mean is modified python 3 ? and use FKDs integrated into FN server?

**Comment by denismakogon** [comment]
Yes, that’s the simplest path to go.

**Comment by rdallman** [comment]
6 weeks of inactivity on this one, re-open if you'd still like a hand! we're in slack too. thanks
