### ISSUE TITLE
Should Fn persist call object as soon as a function execution requested?

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#978]
## problem area

While working with async functions there's certain UX problem with enqueued calls. When someone called a function Fn returns a call ID. I guess the common assumption is that call object will be persisted as soon as possible with the corresponding state, but it appears that call object gets persisted only once - when a call finished.

## how to solve this

I do aware that calling datastore/s3 methods more than once will bring certain overheat and, maybe, consistency problems. However, Fn should persist a call as soon as possible and once it's done - update it with new status and `Completed At` timestamp.

**Comment by rdallman** [comment]
the problem with doing this is we have to then mutate the call state in the data store and have a protocol around 'only once' running (e.g. when a job times out but exists as queued, need a safe way to change to running), so it's not easy to just drop this in. since we're moving to fn server just being a synchronous execution thing, i don't think this is a core issue to address (i.e. is this something we want to do when invoking sync functions?), but we can leave it open as documentation of current behavior since people have asked.

**Comment by rdallman** [comment]
triaging to #281

**Comment by rdallman** [comment]
triaging to #1055
